# Generated by Django 5.2.6 on 2025-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The initial balance when the account was created.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The current calculated balance.', max_digits=15),
        ),
    ]
