# Generated by Django 5.2.6 on 2025-09-28 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Efetivada')], default='PENDING', max_length=10)),
                ('installment_number', models.PositiveIntegerField(blank=True, help_text='The number of the current installment (e.g., 1, 2, 3).', null=True)),
                ('completion_date', models.DateField(blank=True, help_text='The date when the transaction was actually completed/cleared.', null=True)),
                ('recurrence_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('frequency', models.CharField(choices=[('NONE', 'None'), ('INSTALLMENT', 'Parcelado'), ('FIXED', 'Mensal Fixo')], default='NONE', max_length=20)),
                ('installments', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The transaction amount. Always a positive value.', max_digits=15)),
                ('date', models.DateField(help_text='For recurring transactions, this is the date of the first installment.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
